services:
  livebook:
    image: ghcr.io/livebook-dev/livebook
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./:/livebukz:z
      - data:/livebook_data
    environment:
      LIVEBOOK_HOME: /livebukz
      LIVEBOOK_DATA_PATH: /livebook_data

volumes:
  data:
